#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  cat <<USAGE
Layer sweep over VLM model layers (sets LAYER_PATH environment var and runs pipeline)

Usage:
  $(basename "$0") --resource-dir RESOURCE_OUT --output-dir OUT_ROOT
                   [--pipeline PIPELINE.sh]
                   [--start 0 --end 35 --step 1]
                   [--layer-list 0,1,2,...,35]

Required:
  --resource-dir   Preprocessed run dir that contains inference/ (source)
  --output-dir     Output root where per-layer runs will be created

Optional:
  --pipeline       Path to your pipeline script (default: ./run_full_pipeline_without_coroping_omba_diffrentnumber_opf_crops.sh)
  --start          First layer index to run (default: 0)
  --end            Last layer index to run (inclusive, default: 35)
  --step           Step between layers (default: 1)
  --layer-list     Comma list overrides start/end/step (e.g., 0,5,10)

Example:
  ./run_layer_sweep.sh \
    --resource-dir outputs/qwen2_5_10cls_sam/imnet100 \
    --output-dir   outputs/qwen2_5_10cls_sam/imnet100_layer_runs \
    --start 0 --end 35
USAGE
  exit 1
}

PIPELINE="scripts/run_full_pipeline_without_coroping_omba_diffrentnumber_opf_crops.sh"
RESOURCE_DIR=""
OUT_ROOT=""
START=0
END=35
STEP=1
LAYER_LIST=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --resource-dir) RESOURCE_DIR="$2"; shift 2;;
    --output-dir)   OUT_ROOT="$2"; shift 2;;
    --pipeline)     PIPELINE="$2"; shift 2;;
    --start)        START="$2"; shift 2;;
    --end)          END="$2"; shift 2;;
    --step)         STEP="$2"; shift 2;;
    --layer-list)   LAYER_LIST="$2"; shift 2;;
    -h|--help)      usage;;
    *) echo "[ERROR] Unknown arg: $1"; usage;;
  esac
done

[[ -z "$RESOURCE_DIR" || -z "$OUT_ROOT" ]] && echo "[ERROR] --resource-dir and --output-dir are required" && usage
[[ ! -f "$PIPELINE" ]] && echo "[ERROR] Pipeline not found: $PIPELINE" && exit 1
[[ ! -d "$RESOURCE_DIR/inference" ]] && echo "[ERROR] Resource inference not found: $RESOURCE_DIR/inference" && exit 1
if [[ ! -d "$RESOURCE_DIR/features" ]]; then
  echo "[WARN] Resource features not found: $RESOURCE_DIR/features - features will be generated by the pipeline if needed"
fi

mkdir -p "$OUT_ROOT"

# Build layer list if not provided
if [[ -z "$LAYER_LIST" ]]; then
  tmp=()
  i=$START
  while [[ $i -le $END ]]; do
    tmp+=("$i")
    i=$((i + STEP))
  done
  LAYER_LIST="$(IFS=','; echo "${tmp[*]}")"
fi
IFS=',' read -r -a LAYERS <<< "$LAYER_LIST"

echo "[INFO] RESOURCE_DIR = $RESOURCE_DIR"
echo "[INFO] OUT_ROOT     = $OUT_ROOT"
echo "[INFO] layer sweep  = ${LAYERS[*]}"

# Paths inside resource
RESOURCE_INF="$RESOURCE_DIR/inference"
RESOURCE_FEAT="$RESOURCE_DIR/features"

for layer_idx in "${LAYERS[@]}"; do
  RUN_DIR="$OUT_ROOT/layer_${layer_idx}"
  mkdir -p "$RUN_DIR/inference"
  echo "------------------------------------"
  echo "[RUN] layer=$layer_idx"
  echo "[DIR] $RUN_DIR"
  echo "------------------------------------"

  # copy precomputed inference for this layer run (no overwrite)
  rsync -a --ignore-existing "$RESOURCE_INF/" "$RUN_DIR/inference/"

  # Construct LAYER_PATH (user requested format)
  LAYER_PATH="model.language_model.layers.${layer_idx}.post_per_layer_input_norm"

  # run pipeline with this layer
  LAYER_PATH="$LAYER_PATH" OUTPUT_DIR="$RUN_DIR" \
    bash "$PIPELINE" --output-dir "$RUN_DIR"
done

echo "[DONE] Layer sweep finished under: $OUT_ROOT"
